package cmd

type Document struct {
	AppStoreURL   string          `json:"app_store_url"`
	AppTralbumURL string          `json:"app_tralbum_url"`
	Cfg           map[string]bool `json:"cfg"`
	CurrencyData  struct {
		Info struct {
			AED ADollarFixedRateLong  `json:"AED"`
			ALL ADollarFixedRateLong  `json:"ALL"`
			ANG ADollarFixedRateLong  `json:"ANG"`
			ARS ADollarFixedRateLong  `json:"ARS"`
			AUD ADollarFixedRateLong2 `json:"AUD"`
			AWG ADollarFixedRateLong  `json:"AWG"`
			BBD ADollarFixedRateLong  `json:"BBD"`
			BDT ADollarFixedRateLong  `json:"BDT"`
			BHD ADollarFixedRateLong  `json:"BHD"`
			BIF ADollarFixedRateLong  `json:"BIF"`
			BMD ADollarFixedRateLong  `json:"BMD"`
			BND ADollarFixedRateLong  `json:"BND"`
			BOB ADollarFixedRateLong  `json:"BOB"`
			BRL ADollarFixedRateLong  `json:"BRL"`
			BSD ADollarFixedRateLong  `json:"BSD"`
			BTN ADollarFixedRateLong  `json:"BTN"`
			BWP ADollarFixedRateLong  `json:"BWP"`
			BZD ADollarFixedRateLong  `json:"BZD"`
			CAD ADollarFixedRateLong2 `json:"CAD"`
			CHF ADollarFixedRateLong2 `json:"CHF"`
			CLP ADollarFixedRateLong  `json:"CLP"`
			CNY ADollarFixedRateLong  `json:"CNY"`
			COP ADollarFixedRateLong  `json:"COP"`
			CRC ADollarFixedRateLong  `json:"CRC"`
			CVE ADollarFixedRateLong  `json:"CVE"`
			CZK ADollarFixedRateLong  `json:"CZK"`
			DJF ADollarFixedRateLong  `json:"DJF"`
			DKK ADollarFixedRateLong2 `json:"DKK"`
			DOP ADollarFixedRateLong  `json:"DOP"`
			DZD ADollarFixedRateLong  `json:"DZD"`
			EGP ADollarFixedRateLong  `json:"EGP"`
			ETB ADollarFixedRateLong  `json:"ETB"`
			EUR struct {
				ADollar            float64 `json:"a_dollar"`
				FixedRate          int     `json:"fixed_rate"`
				Long               string  `json:"long"`
				MediumMinPrice     float64 `json:"medium_min_price"`
				Payflow            bool    `json:"payflow"`
				Paypal             bool    `json:"paypal"`
				Places             int     `json:"places"`
				Plural             string  `json:"plural"`
				Prefix             string  `json:"prefix"`
				PrefixInformal     string  `json:"prefix_informal"`
				PrefixInformalUTF8 string  `json:"prefix_informal_utf8"`
				PrefixUTF8         string  `json:"prefix_utf8"`
				SmallMinPrice      float64 `json:"small_min_price"`
				SuffixInformal     string  `json:"suffix_informal"`
				Symbol             string  `json:"symbol"`
			} `json:"EUR"`
			FKP ADollarFixedRateLong `json:"FKP"`
			GBP struct {
				ADollar            float64  `json:"a_dollar"`
				FixedRate          int      `json:"fixed_rate"`
				Long               string   `json:"long"`
				MediumMinPrice     float64  `json:"medium_min_price"`
				Payflow            bool     `json:"payflow"`
				Paypal             bool     `json:"paypal"`
				Places             int      `json:"places"`
				Plural             string   `json:"plural"`
				Prefix             string   `json:"prefix"`
				PrefixInformal     string   `json:"prefix_informal"`
				PrefixInformalUTF8 string   `json:"prefix_informal_utf8"`
				PrefixUTF8         string   `json:"prefix_utf8"`
				Slang              []string `json:"slang"`
				SmallMinPrice      float64  `json:"small_min_price"`
				SuffixInformal     string   `json:"suffix_informal"`
				Symbol             string   `json:"symbol"`
			} `json:"GBP"`
			GIP ADollarFixedRateLong  `json:"GIP"`
			GMD ADollarFixedRateLong  `json:"GMD"`
			GNF ADollarFixedRateLong  `json:"GNF"`
			GTQ ADollarFixedRateLong  `json:"GTQ"`
			GYD ADollarFixedRateLong  `json:"GYD"`
			HKD ADollarFixedRateLong2 `json:"HKD"`
			HNL ADollarFixedRateLong  `json:"HNL"`
			HRK ADollarFixedRateLong  `json:"HRK"`
			HTG ADollarFixedRateLong  `json:"HTG"`
			HUF ADollarFixedRateLong  `json:"HUF"`
			IDR ADollarFixedRateLong  `json:"IDR"`
			ILS ADollarFixedRateLong2 `json:"ILS"`
			INR ADollarFixedRateLong  `json:"INR"`
			IQD ADollarFixedRateLong  `json:"IQD"`
			ISK ADollarFixedRateLong  `json:"ISK"`
			JMD ADollarFixedRateLong  `json:"JMD"`
			JOD ADollarFixedRateLong  `json:"JOD"`
			JPY ADollarFixedRateLong  `json:"JPY"`
			KES ADollarFixedRateLong  `json:"KES"`
			KHR ADollarFixedRateLong  `json:"KHR"`
			KMF ADollarFixedRateLong  `json:"KMF"`
			KPW ADollarFixedRateLong  `json:"KPW"`
			KRW ADollarFixedRateLong  `json:"KRW"`
			KWD ADollarFixedRateLong  `json:"KWD"`
			KYD ADollarFixedRateLong  `json:"KYD"`
			KZT ADollarFixedRateLong  `json:"KZT"`
			LAK ADollarFixedRateLong  `json:"LAK"`
			LBP ADollarFixedRateLong  `json:"LBP"`
			LKR ADollarFixedRateLong  `json:"LKR"`
			LRD ADollarFixedRateLong  `json:"LRD"`
			LSL ADollarFixedRateLong  `json:"LSL"`
			LYD ADollarFixedRateLong  `json:"LYD"`
			MAD ADollarFixedRateLong  `json:"MAD"`
			MDL ADollarFixedRateLong  `json:"MDL"`
			MKD ADollarFixedRateLong  `json:"MKD"`
			MMK ADollarFixedRateLong  `json:"MMK"`
			MNT ADollarFixedRateLong  `json:"MNT"`
			MOP ADollarFixedRateLong  `json:"MOP"`
			MRU ADollarFixedRateLong  `json:"MRU"`
			MUR ADollarFixedRateLong  `json:"MUR"`
			MVR ADollarFixedRateLong  `json:"MVR"`
			MWK ADollarFixedRateLong  `json:"MWK"`
			MXN ADollarFixedRateLong  `json:"MXN"`
			MYR ADollarFixedRateLong  `json:"MYR"`
			NAD ADollarFixedRateLong  `json:"NAD"`
			NGN ADollarFixedRateLong  `json:"NGN"`
			NIO ADollarFixedRateLong  `json:"NIO"`
			NOK ADollarFixedRateLong  `json:"NOK"`
			NPR ADollarFixedRateLong  `json:"NPR"`
			NZD ADollarFixedRateLong2 `json:"NZD"`
			OMR ADollarFixedRateLong  `json:"OMR"`
			PAB ADollarFixedRateLong  `json:"PAB"`
			PEN ADollarFixedRateLong  `json:"PEN"`
			PGK ADollarFixedRateLong  `json:"PGK"`
			PHP ADollarFixedRateLong  `json:"PHP"`
			PKR ADollarFixedRateLong  `json:"PKR"`
			PLN ADollarFixedRateLong2 `json:"PLN"`
			PYG ADollarFixedRateLong  `json:"PYG"`
			QAR ADollarFixedRateLong  `json:"QAR"`
			RUB ADollarFixedRateLong  `json:"RUB"`
			RUP ADollarFixedRateLong  `json:"RUP"`
			SAR ADollarFixedRateLong  `json:"SAR"`
			SBD ADollarFixedRateLong  `json:"SBD"`
			SCR ADollarFixedRateLong  `json:"SCR"`
			SEK ADollarFixedRateLong  `json:"SEK"`
			SGD ADollarFixedRateLong2 `json:"SGD"`
			SHP ADollarFixedRateLong  `json:"SHP"`
			SLL ADollarFixedRateLong  `json:"SLL"`
			SOS ADollarFixedRateLong  `json:"SOS"`
			STD ADollarFixedRateLong  `json:"STD"`
			SYP ADollarFixedRateLong  `json:"SYP"`
			SZL ADollarFixedRateLong  `json:"SZL"`
			THB ADollarFixedRateLong  `json:"THB"`
			TND ADollarFixedRateLong  `json:"TND"`
			TOP ADollarFixedRateLong  `json:"TOP"`
			TRY ADollarFixedRateLong  `json:"TRY"`
			TTD ADollarFixedRateLong  `json:"TTD"`
			TWD ADollarFixedRateLong  `json:"TWD"`
			TZS ADollarFixedRateLong  `json:"TZS"`
			UAH ADollarFixedRateLong  `json:"UAH"`
			UGX ADollarFixedRateLong  `json:"UGX"`
			USD struct {
				ADollar            float64  `json:"a_dollar"`
				FixedRate          int      `json:"fixed_rate"`
				Long               string   `json:"long"`
				MediumMinPrice     float64  `json:"medium_min_price"`
				Payflow            bool     `json:"payflow"`
				Paypal             bool     `json:"paypal"`
				Places             int      `json:"places"`
				Plural             string   `json:"plural"`
				Prefix             string   `json:"prefix"`
				PrefixInformal     string   `json:"prefix_informal"`
				PrefixInformalUTF8 string   `json:"prefix_informal_utf8"`
				PrefixUTF8         string   `json:"prefix_utf8"`
				Slang              []string `json:"slang"`
				SmallMinPrice      float64  `json:"small_min_price"`
				SuffixInformal     string   `json:"suffix_informal"`
				Symbol             string   `json:"symbol"`
			} `json:"USD"`
			UYU ADollarFixedRateLong `json:"UYU"`
			VUV ADollarFixedRateLong `json:"VUV"`
			WST ADollarFixedRateLong `json:"WST"`
			XAF ADollarFixedRateLong `json:"XAF"`
			XCD ADollarFixedRateLong `json:"XCD"`
			XOF ADollarFixedRateLong `json:"XOF"`
			XPF ADollarFixedRateLong `json:"XPF"`
			YER ADollarFixedRateLong `json:"YER"`
			ZAR ADollarFixedRateLong `json:"ZAR"`
			ZMW ADollarFixedRateLong `json:"ZMW"`
		} `json:"info"`
		List  []string           `json:"list"`
		Rates map[string]float64 `json:"rates"`
	} `json:"currency_data"`
	DigitalItems       []ArrivalDateArtIDArtist `json:"digital_items"`
	DownloadDifficulty string                   `json:"download_difficulty"`
	DownloadFormat     string                   `json:"download_format"`
	DownloadFormats    []struct {
		DbColumn      string `json:"db_column"`
		Description   string `json:"description"`
		FileExtension string `json:"file_extension"`
		HasVariants   *bool  `json:"has_variants,omitempty"`
		MimeType      string `json:"mime_type"`
		Name          string `json:"name"`
	} `json:"download_formats"`
	DownloadItems    []ArrivalDateArtIDArtist `json:"download_items"`
	GiftDownloadPage bool                     `json:"gift_download_page"`
	HasDownloads     bool                     `json:"has_downloads"`
	HelpCenterURL    string                   `json:"help_center_url"`
	Identities       struct {
		Partner bool `json:"partner"`
	} `json:"identities"`
	InvisibleRecaptchaPublicKey string `json:"invisible_recaptcha_public_key"`
	IsRedownload                bool   `json:"is_redownload"`
	Languages                   struct {
		En string `json:"en"`
		Fr string `json:"fr"`
		Ja string `json:"ja"`
	} `json:"languages"`
	Locale       string `json:"locale"`
	LocalizePage bool   `json:"localize_page"`
	LoggedOutFan struct {
		ArtistMessageEmailsEnabled bool     `json:"artist_message_emails_enabled"`
		Bio                        string   `json:"bio"`
		CreateDate                 string   `json:"create_date"`
		DownloadEncoding           int      `json:"download_encoding"`
		Enabled                    bool     `json:"enabled"`
		FavGenreID                 int      `json:"fav_genre_id"`
		FavGenreName               string   `json:"fav_genre_name"`
		ID                         int      `json:"id"`
		ImageID                    int      `json:"image_id"`
		Locale                     string   `json:"locale"`
		MontageImageID             int      `json:"montage_image_id"`
		Name                       string   `json:"name"`
		NotifierEnabled            bool     `json:"notifier_enabled"`
		PaymentType                string   `json:"payment_type"`
		PaypalEmails               []string `json:"paypal_emails"`
		Private                    bool     `json:"private"`
		ReleaseNoticeEmailsEnabled bool     `json:"release_notice_emails_enabled"`
		TrackpipeURL               string   `json:"trackpipe_url"`
		TrackpipeURLHTTPS          string   `json:"trackpipe_url_https"`
		Username                   string   `json:"username"`
		Verified                   bool     `json:"verified"`
		WebsiteURL                 string   `json:"website_url"`
		WishlistEmailsEnabled      bool     `json:"wishlist_emails_enabled"`
	} `json:"logged_out_fan"`
	MobileAppURL       string                   `json:"mobile_app_url"`
	Multidownload      bool                     `json:"multidownload"`
	Packages           []ArrivalDateArtIDArtist `json:"packages"`
	Platform           string                   `json:"platform"`
	PlayStoreURL       string                   `json:"play_store_url"`
	RecaptchaPublicKey string                   `json:"recaptcha_public_key"`
	SignupParams       struct {
		ActivationSig string `json:"activation_sig"`
		ActivationURL string `json:"activation_url"`
		EmailSig      string `json:"email_sig"`
		Genres        []struct {
			ID       int    `json:"id"`
			Name     string `json:"name"`
			NormName string `json:"norm_name"`
			Value    string `json:"value"`
		} `json:"genres"`
		IsMobile  bool `json:"isMobile"`
		IsPhone   bool `json:"is_phone"`
		SaveCard  bool `json:"save_card"`
		Subgenres map[string][]struct {
			Name     string `json:"name"`
			NormName string `json:"norm_name"`
			Value    string `json:"value"`
		} `json:"subgenres"`
	} `json:"signup_params"`
	Templglobals struct {
		EndpointMobilized bool `json:"endpoint_mobilized"`
		IsPhone           bool `json:"is_phone"`
	} `json:"templglobals"`
	UnsupportedDevice bool `json:"unsupported_device"`
}
type DescriptionEncodingNameSizeMb struct {
	Description  string `json:"description"`
	EncodingName string `json:"encoding_name"`
	SizeMb       string `json:"size_mb"`
	URL          string `json:"url"`
}
type ADollarFixedRateLong struct {
	ADollar            float64    `json:"a_dollar"`
	FixedRate          int    `json:"fixed_rate"`
	Long               string `json:"long"`
	MediumMinPrice     float64 `json:"medium_min_price"`
	Payflow            bool   `json:"payflow"`
	Paypal             bool   `json:"paypal"`
	Places             int    `json:"places"`
	Plural             string `json:"plural"`
	Prefix             string `json:"prefix"`
	PrefixInformal     string `json:"prefix_informal"`
	PrefixInformalUTF8 string `json:"prefix_informal_utf8"`
	PrefixUTF8         string `json:"prefix_utf8"`
	SmallMinPrice      float64    `json:"small_min_price"`
	SuffixInformal     string `json:"suffix_informal"`
	Symbol             string `json:"symbol"`
}
type ADollarFixedRateLong2 struct {
	ADollar            float64     `json:"a_dollar"`
	FixedRate          int     `json:"fixed_rate"`
	Long               string  `json:"long"`
	MediumMinPrice     float64     `json:"medium_min_price"`
	Payflow            bool    `json:"payflow"`
	Paypal             bool    `json:"paypal"`
	Places             int     `json:"places"`
	Plural             string  `json:"plural"`
	Prefix             string  `json:"prefix"`
	PrefixInformal     string  `json:"prefix_informal"`
	PrefixInformalUTF8 string  `json:"prefix_informal_utf8"`
	PrefixUTF8         string  `json:"prefix_utf8"`
	SmallMinPrice      float64 `json:"small_min_price"`
	SuffixInformal     string  `json:"suffix_informal"`
	Symbol             string  `json:"symbol"`
}
type PackageURLHints struct {
	Subdomain string `json:"subdomain"`
}
type URLHints struct {
	ItemType  string `json:"item_type"`
	Slug      string `json:"slug"`
	Subdomain string `json:"subdomain"`
}
type ArrivalDateArtIDArtist struct {
	ArrivalDate             string                                   `json:"arrival_date"`
	ArtID                   int                                      `json:"art_id"`
	Artist                  string                                   `json:"artist"`
	BandEnabled             int                                      `json:"band_enabled"`
	BandID                  int                                      `json:"band_id"`
	BandName                string                                   `json:"band_name"`
	BuyerID                 int                                      `json:"buyer_id"`
	BuyerType               string                                   `json:"buyer_type"`
	Currency                string                                   `json:"currency"`
	Desc                    string                                   `json:"desc"`
	DescTrackCount          int                                      `json:"desc_track_count"`
	DownloadID              int                                      `json:"download_id"`
	DownloadPref            int                                      `json:"download_pref"`
	DownloadType            string                                   `json:"download_type"`
	DownloadTypeStr         string                                   `json:"download_type_str"`
	Downloads               map[string]DescriptionEncodingNameSizeMb `json:"downloads"`
	EstimatedShipDate       string                                   `json:"estimated_ship_date"`
	EstimatedShipDatePassed bool                                     `json:"estimated_ship_date_passed"`
	FulfillmentDays         int                                      `json:"fulfillment_days"`
	GenreID                 int                                      `json:"genre_id"`
	GiftLink                string                                   `json:"gift_link"`
	HasEnhancedSeller       int                                      `json:"has_enhanced_seller"`
	ImageID                 int                                      `json:"image_id"`
	IncludesDigital         bool                                     `json:"includes_digital"`
	IsPureFree              bool                                     `json:"is_pure_free"`
	IsTralbumAttached       bool                                     `json:"is_tralbum_attached"`
	ItemID                  int                                      `json:"item_id"`
	ItemType                string                                   `json:"item_type"`
	MinPrice                float64                                  `json:"min_price"`
	NotifyMe                bool                                     `json:"notify_me"`
	NotifyMeLabel           bool                                     `json:"notify_me_label"`
	PackageImageID          int                                      `json:"package_image_id"`
	PackageReleaseDate      string                                   `json:"package_release_date"`
	PackageSubdomain        string                                   `json:"package_subdomain"`
	PackageTitle            string                                   `json:"package_title"`
	PackageTypeID           int                                      `json:"package_type_id"`
	PackageTypeName         string                                   `json:"package_type_name"`
	PackageURLHints         PackageURLHints                          `json:"package_url_hints"`
	PageURL                 string                                   `json:"page_url"`
	PaidFor                 bool                                     `json:"paid_for"`
	PaymentAmt              string                                   `json:"payment_amt"`
	PaymentEmail            string                                   `json:"payment_email"`
	PaymentID               int                                      `json:"payment_id"`
	PaymentType             string                                   `json:"payment_type"`
	PhysicalOrdersURL       string                                   `json:"physical_orders_url"`
	Quantity                int                                      `json:"quantity"`
	Ready                   bool                                     `json:"ready"`
	ReleaseDate             string                                   `json:"release_date"`
	SaleID                  int                                      `json:"sale_id"`
	SaleItemState           string                                   `json:"sale_item_state"`
	Shareable               bool                                     `json:"shareable"`
	Shippable               int                                      `json:"shippable"`
	ShippingBannerEnabled   int                                      `json:"shipping_banner_enabled"`
	SoldDate                string                                   `json:"sold_date"`
	Subtitle                string                                   `json:"subtitle"`
	ThumbTitle              string                                   `json:"thumb_title"`
	Title                   string                                   `json:"title"`
	TrackCount              int                                      `json:"track_count"`
	TralbumID               int                                      `json:"tralbum_id"`
	Type                    string                                   `json:"type"`
	URLHints                URLHints                                 `json:"url_hints"`
	UnitPrice               float64                                   `json:"unit_price"`
}
